name: srdn

nfeatures:
  hidden: 64
  upscale: 128
nlayers: 16
usmethod: replicate # replicate # transpose
loss_fn: l2
kernel_size:
  features: 3
  hidden: 3
  output: 9

downscale_factors: [2,2]
ups_mode: bicubic