nfuture: 0
loss_fn: 'l2'
batch_size: 1
num_workers: 0
persistent_workers: False

grid: "equiangular"
in_chans: 178
out_chans: 83
pos_embed: "lat"
use_mlp: False
normalization_layer: 'none'
activation_function: 'relu'
spectral_transform: 'sht'
operator_type: 'driscoll-healy'
scale_factor: 3
embed_dim:  256
num_layers: 4
encoder_layers: 1
mlp_ratio: 2.0
drop_rate: 0.0
drop_path_rate: 0.0
hard_thresholding_fraction:  1.0
big_skip:  False
factorization: None
separable: False
rank:  128
inner_skip: "none"
outer_skip: "identity"
training_version: 'merra2-sfno.1'

