nfuture: 0
loss_fn: 'l2'
batch_size: 1
num_workers: 0
persistent_workers: False
grid: "equiangular"
embed_shape: (256,512)
in_chans: 178
out_chans: 83
pos_embed: "lat"
use_mlp: True
normalization_layer: 'none'
activation_function: 'relu'
spectral_transform: 'sht'
operator_type: 'driscoll-healy'
downscale_factors: [2,2,2]
embed_dim:  256
num_layers: 4                 # Total number of layers
num_downscale_layers: 2       # Number of layers out of total at downscale resolution
encoder_layers: 3
mlp_ratio: 1.0
drop_rate: 0.0
drop_path_rate: 0.0
hard_thresholding_fraction:  1.0
big_skip:  False
factorization: None
separable: False
rank:  128
inner_skip: "linear"
outer_skip: "identity"
training_version: 'merra2-sres.1'

