name: srdn

nfeatures:
  hidden: 64
  upscale: 128
  output: 1
nrlayers: 16
downscale_factors: [2]
usmethod: replicate # replicate # transpose
loss_fn: l2
kernel_size:
  features: 3
  hidden: 3
  output: 9